# inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'db/schema.rb'
   - 'db/**/*'
   - 'vendor/bundle/**/*'

  DisplayCopNames: true

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes