inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'db/schema.rb'
   - 'db/**/*'
   - 'vendor/bundle/**/*'
   - 'app/models/user.rb'

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false