development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: trains_development
  pool:     5
  username: glaux
  password: server
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: trains_test
  pool:     5
  username: glaux
  password: server
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: trains_production
  pool:     5
  username: glaux
  password: server
  template: template0
